name: Release Preview

on:
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  release_preview:
    uses: OpenVoiceOS/gh-automations/.github/workflows/release-preview.yml@dev
    with:
      package_name: 'hivemind_mic_satellite'
      version_file: 'hivemind_mic_sat/version.py'
